type Account {
  name: String
  visits: [Visit!] @relation
}

type Visit {
  ip: String
  userAgent: String
  location: String
  referrer: String
  noscript: Boolean
  created: Time!
  account: Account!
}

type Query {
  allVisits: [Visit!]
}
